server:
  port: 5555

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

## Lista as rotas encontradas no Eureka
management:
  endpoints:
    web:
      exposure:
        include:
          - "routes"